function todayIsoDate(){const n=new Date();return `${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-${String(n.getDate()).padStart(2,'0')}`;}
const MODERNIZATION_ELEMENTS=[
{id:'roof',label:'Dacherneuerung inkl. Wärmedämmung',max:4,info:'Dach inkl. Dämmung: bis 5 Jahre = 4 Punkte, 6–10 Jahre = 3 Punkte, 11–15 Jahre = 2 Punkte, 16–20 Jahre = 1 Punkt, älter/nicht modernisiert = 0 Punkte.'},
{id:'windows',label:'Fenster und Außentüren',max:2,info:'Fenster/Außentüren: bis 10 Jahre = 2 Punkte, 11–20 Jahre = 1 Punkt, älter/nicht modernisiert = 0 Punkte.'},
{id:'systems',label:'Leitungssysteme Strom/Gas/Wasser/Abwasser',max:2,info:'Leitungssysteme: umfassend erneuert = 2 Punkte, teilweise/älter modernisiert = 1 Punkt, nicht modernisiert = 0 Punkte. Modellkonform zum Marktbericht prüfen.'},
{id:'heating',label:'Heizungsanlage',max:2,info:'Heizung: bis 10 Jahre = 2 Punkte, 11–20 Jahre = 1 Punkt, älter/nicht modernisiert = 0 Punkte.'},
{id:'facade',label:'Wärmedämmung Außenwände',max:4,info:'Außenwanddämmung: bis 5 Jahre = 4 Punkte, 6–10 Jahre = 3 Punkte, 11–15 Jahre = 2 Punkte, 16–20 Jahre = 1 Punkt, älter/nicht modernisiert = 0 Punkte.'},
{id:'bath',label:'Bäder',max:2,info:'Bäder: modern/umfassend erneuert = 2 Punkte, teilweise/älter modernisiert = 1 Punkt, nicht modernisiert = 0 Punkte.'},
{id:'interior',label:'Innenausbau Decken/Fußböden/Treppen',max:2,info:'Innenausbau: umfassend modernisiert = 2 Punkte, teilweise modernisiert = 1 Punkt, nicht modernisiert = 0 Punkte.'},
{id:'layout',label:'wesentliche Grundrissverbesserung',max:2,info:'Grundrissverbesserung: wesentliche Verbesserung = 1–2 Punkte. Keine zeitabhängige Bauteilmodernisierung, sondern funktionaler Eingriff.'}
];
const DEFAULT_MODERNIZATION=Object.fromEntries(MODERNIZATION_ELEMENTS.map(i=>[i.id,0]));
const DEFAULT_CASE={objectName:'Neues Objekt',valuationDate:todayIsoDate(),borisAddress:'',constructionYear:'',totalArea:'',baseLandValuePerSqm:'',timeAdjustmentFactor:1,landFeatureFactor:1,plotArea:'',relevantFloorArea:'',buildingLandArea:'',gardenArea:0,gardenFactor:.1,operatingCostRate:12.58,propertyYield:1.5,totalUsefulLife:80,remainingLife:40,marketAdjustment:0,bogDeductions:0,bogAdditions:0,purchasePrice:'',purchaseCostsRate:10,negotiationBuffer:5,modernization:DEFAULT_MODERNIZATION};
let brwHistory=[];let modernization={...DEFAULT_MODERNIZATION};let units=[{name:'Einheit 1',area:0,rentMode:'sqm',rentPerSqm:0,monthlyRent:0,factor:1}];
function numberValue(id){const e=document.getElementById(id);return e?parseFloat(String(e.value).replace(',','.'))||0:0}function textValue(id){const e=document.getElementById(id);return e?e.value:''}function setValue(id,v){const e=document.getElementById(id);if(e)e.value=v??''}function setText(id,v){const e=document.getElementById(id);if(e)e.textContent=v}function euro(v){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v||0)}function percent(v){return `${(v||0).toFixed(2)} %`}function getYearFromDate(s){const d=s?new Date(`${s}T12:00:00`):new Date();return Number.isFinite(d.getFullYear())?d.getFullYear():new Date().getFullYear()}function numberValueFromElement(e){return parseFloat(String(e.value).replace(',','.'))||0}
function modernizationPoints(){return MODERNIZATION_ELEMENTS.reduce((s,i)=>s+(Number(modernization[i.id])||0),0)}function buildingAge(d){return Math.max(0,getYearFromDate(d.valuationDate)-(Number(d.constructionYear)||getYearFromDate(d.valuationDate)))}function calculateModifiedRND(d){const gnd=Math.max(1,Number(d.totalUsefulLife)||80),age=Math.min(buildingAge(d),gnd),baseRnd=Math.max(0,gnd-age),points=Math.max(0,Math.min(20,modernizationPoints())),rejuvenation=age*(points/20)*.55,rnd=Math.round(Math.min(gnd,Math.max(baseRnd,baseRnd+rejuvenation)));return{gnd,age,baseRnd,points,rnd,info:`RND transparent: Bewertungsjahr ${getYearFromDate(d.valuationDate)}; Baujahr ${d.constructionYear||'–'}; Alter ${age} J.; GND ${gnd} J.; Basis-RND = ${gnd} − ${age} = ${baseRnd} J.; Modernisierung ${points}/20 Punkte. Fachlich final: Punkte + Alter + GND ziehen Tabellenwert/Faktor aus Grundstücksmarktbericht/ImmoWertA Anlage 2; daraus modifizierte RND; daraus Kapitalisierungsfaktor/Vervielfältiger. Aktuell noch Näherung: Alter × Punkte/20 × 0,55 = ${rejuvenation.toFixed(1)} J.; angesetzte RND = ${rnd} J.`}}
function calculateBrwTimeFactor(currentBrw,valuationYear){const currentYear=valuationYear-1,map=new Map();brwHistory.map(p=>({year:Number(p.year),value:Number(p.value)})).filter(p=>p.year>0&&p.value>0&&p.year!==currentYear).forEach(p=>map.set(p.year,p.value));if(!currentBrw||map.size===0)return{factor:1,info:'BRW-Zeitfaktor: keine auswertbare Historie angegeben, daher Faktor 1,00.'};const pts=[...Array.from(map,([year,value])=>({year,value})),{year:currentYear,value:currentBrw}].sort((a,b)=>a.year-b.year),first=pts[0],last=pts[pts.length-1],span=last.year-first.year;if(span<=0)return{factor:1,info:'BRW-Zeitfaktor: Historie nicht auswertbar, daher Faktor 1,00.'};const trend=(last.value-first.value)/span,target=currentBrw+trend*(valuationYear-currentYear),factor=target>0?target/currentBrw:1;return{factor,info:`BRW-Zeitfaktor: aktueller BRW ${currentYear} = ${euro(currentBrw)}/m²; Trend aus ${first.year} (${euro(first.value)}/m²) bis ${last.year} (${euro(last.value)}/m²); Zieljahr ${valuationYear} → ${euro(target)}/m²; Faktor ${factor.toFixed(3)}.`}}
function calculateCapitalizationFactor(y,n){const p=y/100;if(n<=0)return 0;if(p<=0)return n;const q=1+p;return(Math.pow(q,n)-1)/(Math.pow(q,n)*p)}function unitAnnualIncome(u){return u.rentMode==='monthly'?(Number(u.monthlyRent)||0)*12*((Number(u.factor)||0)):(Number(u.area)||0)*(Number(u.rentPerSqm)||0)*12*((Number(u.factor)||0))}
function readCase(){const valuationYear=getYearFromDate(textValue('valuationDate')),brwFactor=calculateBrwTimeFactor(numberValue('baseLandValuePerSqm'),valuationYear);setValue('timeAdjustmentFactor',brwFactor.factor.toFixed(3));setText('brwTrendInfo',brwFactor.info);const d={objectName:textValue('objectName'),valuationDate:textValue('valuationDate'),borisAddress:textValue('borisAddress'),constructionYear:numberValue('constructionYear'),totalArea:numberValue('totalArea'),baseLandValuePerSqm:numberValue('baseLandValuePerSqm'),timeAdjustmentFactor:brwFactor.factor,landFeatureFactor:numberValue('landFeatureFactor'),plotArea:numberValue('plotArea'),relevantFloorArea:numberValue('relevantFloorArea'),buildingLandArea:numberValue('buildingLandArea'),gardenArea:numberValue('gardenArea'),gardenFactor:numberValue('gardenFactor'),operatingCostRate:numberValue('operatingCostRate'),propertyYield:numberValue('propertyYield'),totalUsefulLife:numberValue('totalUsefulLife')||80,remainingLife:numberValue('remainingLife'),marketAdjustment:numberValue('marketAdjustment'),bogDeductions:numberValue('bogDeductions'),bogAdditions:numberValue('bogAdditions'),purchasePrice:numberValue('purchasePrice'),purchaseCostsRate:numberValue('purchaseCostsRate'),negotiationBuffer:numberValue('negotiationBuffer'),units,brwHistory,modernization};const r=calculateModifiedRND(d);setValue('remainingLife',r.rnd);setValue('modernizationPointsDisplay',`${r.points} / 20`);setText('rndInfo',r.info);setText('modernizationPoints',`${r.points} / 20`);setText('rndSummary',`RND ${r.rnd} Jahre`);d.remainingLife=r.rnd;return d}
function calculate(d){const actualWgfz=d.plotArea>0&&d.relevantFloorArea>0?d.relevantFloorArea/d.plotArea:0,adjustedBrw=d.baseLandValuePerSqm*d.timeAdjustmentFactor*d.landFeatureFactor,landValue=adjustedBrw*d.buildingLandArea+adjustedBrw*d.gardenArea*d.gardenFactor,grossIncome=d.units.reduce((s,u)=>s+unitAnnualIncome(u),0),operatingCosts=grossIncome*d.operatingCostRate/100,netIncome=grossIncome-operatingCosts,landInterest=landValue*d.propertyYield/100,buildingIncome=netIncome-landInterest,multiplier=calculateCapitalizationFactor(d.propertyYield,d.remainingLife),buildingValue=buildingIncome*multiplier,preliminaryIncomeValue=buildingValue+landValue,marketAdjustedValue=preliminaryIncomeValue*(1+d.marketAdjustment/100),bogTotal=d.bogAdditions-d.bogDeductions,incomeValue=marketAdjustedValue+bogTotal,targetOffer=incomeValue*(1-d.negotiationBuffer/100),totalAcquisitionCost=d.purchasePrice*(1+d.purchaseCostsRate/100),valueGap=incomeValue-totalAcquisitionCost,rentMultiplier=grossIncome>0?d.purchasePrice/grossIncome:0,grossYield=d.purchasePrice>0?grossIncome/d.purchasePrice*100:0,netYield=d.purchasePrice>0?netIncome/d.purchasePrice*100:0;return{actualWgfz,adjustedBrw,landValue,grossIncome,operatingCosts,netIncome,landInterest,buildingIncome,multiplier,buildingValue,preliminaryIncomeValue,marketAdjustedValue,bogTotal,incomeValue,targetOffer,totalAcquisitionCost,valueGap,rentMultiplier,grossYield,netYield}}
function renderModernization(){const c=document.getElementById('modernizationContainer');if(!c)return;c.innerHTML=MODERNIZATION_ELEMENTS.map(i=>{const v=modernization[i.id]||0;return `<div class="modernization-row"><div class="modernization-label"><span>${i.label}<span class="info-tooltip" data-tooltip="${i.info}">i</span></span><strong data-modernization-value="${i.id}">${v} / ${i.max}</strong></div><div class="modernization-control"><input type="range" min="0" max="${i.max}" step="1" value="${v}" data-modernization-id="${i.id}"></div></div>`}).join('')}
function updateModernizationDisplay(){MODERNIZATION_ELEMENTS.forEach(i=>{const e=document.querySelector(`[data-modernization-value="${i.id}"]`);if(e)e.textContent=`${modernization[i.id]||0} / ${i.max}`})}
function renderUnits(){const c=document.getElementById('unitsContainer');if(!c)return;c.innerHTML=units.map((u,i)=>`<div class="unit-card"><div class="unit-head"><strong>${u.name||`Einheit ${i+1}`}</strong><button type="button" data-remove-unit="${i}" ${units.length===1?'disabled':''}>Entfernen</button></div><div class="grid three compact-grid"><label>Name<input data-unit-field="name" data-unit-index="${i}" value="${u.name||''}" /></label><label>Fläche<input type="number" data-unit-field="area" data-unit-index="${i}" value="${u.area||0}" min="0" step="1" /><small>m²</small></label><label>Mietmodus<select data-unit-field="rentMode" data-unit-index="${i}"><option value="sqm" ${u.rentMode==='sqm'?'selected':''}>€/m²</option><option value="monthly" ${u.rentMode==='monthly'?'selected':''}>Monatsmiete</option></select></label><label>Miete €/m²<input type="number" data-unit-field="rentPerSqm" data-unit-index="${i}" value="${u.rentPerSqm||0}" min="0" step="0.1" /></label><label>Monatsmiete<input type="number" data-unit-field="monthlyRent" data-unit-index="${i}" value="${u.monthlyRent||0}" min="0" step="10" /></label><label>Faktor<input type="number" data-unit-field="factor" data-unit-index="${i}" value="${u.factor||1}" min="0" step="0.1" /></label></div><small>Jahresrohertrag: ${euro(unitAnnualIncome(u))}</small></div>`).join('')}
function renderBrwHistory(){const c=document.getElementById('brwHistoryContainer');if(!c)return;c.innerHTML=brwHistory.map((p,i)=>`<div class="history-row"><label>Jahr<input type="number" data-history-field="year" data-history-index="${i}" value="${p.year||''}" min="1900" max="2100" step="1" /></label><label>BRW<input type="number" data-history-field="value" data-history-index="${i}" value="${p.value||''}" min="0" step="10" /></label><button type="button" data-remove-history="${i}">Entfernen</button></div>`).join('')}
function update(){const d=readCase(),r=calculate(d);setValue('actualWgfz',r.actualWgfz?r.actualWgfz.toFixed(2):'');setValue('unitCountDisplay',d.units.length);setText('headlineValue',euro(r.incomeValue));setText('headlineMeta',`${d.objectName} · ${d.valuationDate}`);setText('objectSummary',`${d.borisAddress||'keine Adresse'} · ${d.totalArea||0} m²`);setText('landSummary',euro(r.landValue));setText('incomeSummary',`${euro(r.grossIncome)} / Jahr`);setText('modelSummary',`LZ ${d.propertyYield.toFixed(2)} % · RND ${d.remainingLife} J.`);setText('bogSummary',euro(r.bogTotal));setText('purchaseSummary',`Ziel ${euro(r.targetOffer)}`);['adjustedBrw','landValue','grossIncome','operatingCosts','netIncome','landInterest','buildingIncome','buildingValue','preliminaryIncomeValue','bogTotal','incomeValue','targetOffer','totalAcquisitionCost','valueGap'].forEach(id=>setText(id,id==='adjustedBrw'?`${euro(r[id])} / m²`:euro(r[id])));setText('multiplier',r.multiplier.toFixed(3));setText('rentMultiplier',`${r.rentMultiplier.toFixed(1)}x`);setText('grossYield',percent(r.grossYield));setText('netYield',percent(r.netYield));let v='Neutral. Die Parameter prüfen und mit Marktbericht/Gutachten abgleichen.';if(r.buildingIncome<0)v='Warnung: Bodenwertverzinsung liegt über dem Reinertrag. Ertragswertverfahren kritisch prüfen.';else if(r.valueGap<-100000)v='Kaufpreis inkl. Nebenkosten liegt deutlich über dem Ertragswert. Nur mit Abschlag oder Zusatzpotenzial interessant.';else if(r.valueGap>100000)v='Ertragswert liegt deutlich über Kaufpreis inkl. Nebenkosten. Wirtschaftlich interessant, Risiken prüfen.';setText('verdict',v);window.currentSummary=buildSummary(d,r)}
function buildSummary(d,r){return `# Kurzbewertung ${d.objectName}\n\nErtragswert: ${euro(r.incomeValue)}\nZiel-Angebot: ${euro(r.targetOffer)}\nBodenwert: ${euro(r.landValue)}\nJahresrohertrag: ${euro(r.grossIncome)}\nLiegenschaftszins: ${d.propertyYield.toFixed(2)} %\nRND: ${d.remainingLife} Jahre\nModernisierungspunkte: ${modernizationPoints()} / 20\n`}
function loadCase(data){const m={...DEFAULT_CASE,...data};if(!m.valuationDate||m.valuationDate==='2024-01-08')m.valuationDate=todayIsoDate();Object.entries(m).forEach(([k,v])=>{if(!['units','brwHistory','modernization'].includes(k))setValue(k,v)});units=m.units?.length?m.units:[{name:'Einheit 1',area:0,rentMode:'sqm',rentPerSqm:0,monthlyRent:0,factor:1}];brwHistory=m.brwHistory||[];modernization={...DEFAULT_MODERNIZATION,...(m.modernization||{})};renderUnits();renderBrwHistory();renderModernization();update()}
function openExternal(url){window.open(url,'_blank','noopener,noreferrer')}function encodedAddress(){return encodeURIComponent(textValue('borisAddress')||textValue('objectName')||'Stuttgart')}
document.addEventListener('input',e=>{const t=e.target,ui=t.dataset.unitIndex,uf=t.dataset.unitField,hi=t.dataset.historyIndex,hf=t.dataset.historyField,mid=t.dataset.modernizationId;if(uf!==undefined){units[ui][uf]=t.type==='number'?numberValueFromElement(t):t.value;renderUnits()}if(hf!==undefined){brwHistory[hi][hf]=numberValueFromElement(t)}if(mid!==undefined){modernization[mid]=numberValueFromElement(t);updateModernizationDisplay()}update()});
document.addEventListener('click',e=>{const ru=e.target.dataset.removeUnit,rh=e.target.dataset.removeHistory;if(ru!==undefined&&units.length>1){units.splice(Number(ru),1);renderUnits();update()}if(rh!==undefined){brwHistory.splice(Number(rh),1);renderBrwHistory();update()}});
document.getElementById('addUnit')?.addEventListener('click',()=>{units.push({name:`Einheit ${units.length+1}`,area:0,rentMode:'sqm',rentPerSqm:0,monthlyRent:0,factor:1});renderUnits();update()});document.getElementById('addBrwHistory')?.addEventListener('click',()=>{const y=getYearFromDate(textValue('valuationDate'))-1;brwHistory.push({year:y-1-brwHistory.length,value:0});renderBrwHistory();update()});document.getElementById('saveCase')?.addEventListener('click',()=>localStorage.setItem('immowert-case',JSON.stringify(readCase())));document.getElementById('resetCase')?.addEventListener('click',()=>{localStorage.removeItem('immowert-case');brwHistory=[];units=[{name:'Einheit 1',area:0,rentMode:'sqm',rentPerSqm:0,monthlyRent:0,factor:1}];modernization={...DEFAULT_MODERNIZATION};loadCase({...DEFAULT_CASE,valuationDate:todayIsoDate()})});document.getElementById('copySummary')?.addEventListener('click',async()=>await navigator.clipboard.writeText(window.currentSummary||''));document.getElementById('openBoris')?.addEventListener('click',()=>openExternal(`https://www.google.com/search?q=${encodedAddress()}+BORIS-BW+Bodenrichtwert`));document.getElementById('openGeoportal')?.addEventListener('click',()=>openExternal(`https://www.google.com/search?q=${encodedAddress()}+Geoportal+Stuttgart+Bodenrichtwert`));
const savedCase=localStorage.getItem('immowert-case');loadCase(savedCase?JSON.parse(savedCase):{...DEFAULT_CASE,valuationDate:todayIsoDate()});
