function switchView(viewName){document.querySelectorAll('[data-view]').forEach(v=>v.classList.toggle('active',v.dataset.view===viewName));document.querySelectorAll('[data-switch-view]').forEach(b=>b.classList.toggle('active',b.dataset.switchView===viewName))}
function updateBrandLabel(){const a=document.querySelector('.ribbon-eyebrow');if(a)a.textContent='LAB7784 Immowert';const b=document.querySelector('.hero .eyebrow');if(b)b.textContent='LAB7784 Immowert · MVP';document.title='LAB7784 Immowert – Analyse & Datenerhebung'}
function money(v){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(v)||0)}
function num(v,d=2){return(Number(v)||0).toLocaleString('de-DE',{minimumFractionDigits:d,maximumFractionDigits:d})}
function esc(v){return String(v??'').replace(/[&<>"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[s]))}
let bogItems=JSON.parse(localStorage.getItem('immowert-bog-items')||'[]');
function saveBogItems(){localStorage.setItem('immowert-bog-items',JSON.stringify(bogItems))}
function sumBog(type){return bogItems.filter(i=>i.type===type).reduce((s,i)=>s+(Number(i.amount)||0),0)}
function syncBogTotals(){if(typeof setValue!=='function')return;setValue('bogAdditions',sumBog('add'));setValue('bogDeductions',sumBog('deduct'))}
const FALLBACK_PROFILES=[
{id:'stuttgart-2024',name:'Stuttgart 2024',quality:'hoch',landValue:{model:'wgfz',required:['baseLandValuePerSqm','plotArea','wgfzSoll','relevantFloorArea'],optional:['gardenArea','gardenFactor','manualLocationFactor'],disabled:[],formula:'BRW × Zeitfaktor × UK(WGFZ_ist) / UK(WGFZ_soll) × sonstiger Faktor'},yields:[['mfh','Reines Mehrfamilienhaus',1.5,'offiziell lokal','hoch'],['mfh20','MFH Gewerbe ≤20 %',1.4,'offiziell lokal','hoch'],['mfh50','MFH Gewerbe 21–50 %',2.1,'offiziell lokal','hoch'],['mixed','Gemischt >50 % Gewerbe',2.2,'offiziell lokal','hoch'],['office','Bürogebäude',3.6,'offiziell lokal','hoch']]},
{id:'reutlingen-2025',name:'Reutlingen 2025',quality:'mittel/hoch',landValue:{model:'no_wgfz_individual_housing',required:['baseLandValuePerSqm','plotArea','buildingLandArea'],optional:['gardenArea','gardenFactor','manualLocationFactor'],disabled:['wgfzSoll','relevantFloorArea','wgfzCorrectionFactor'],formula:'BRW × Zeitfaktor × sachverständiger Faktor; keine Regel-WGFZ-Umrechnung im individuellen Wohnungsbau'},yields:[['efh','EFH/ZFH',1.0,'offiziell lokal','hoch'],['34fh','Drei-/Vierfamilienhaus',1.2,'offiziell lokal','mittel'],['mfh','5–20-Familienhaus',1.9,'offiziell lokal','mittel'],['office','Büro/Praxis',2.9,'offiziell lokal','mittel']]},
{id:'fellbach-2022',name:'Fellbach 2022',quality:'niedrig/mittel',landValue:{model:'manual_no_local_tables',required:['baseLandValuePerSqm','plotArea','buildingLandArea'],optional:['gardenArea','gardenFactor','manualLocationFactor'],disabled:['wgfzSoll','wgfzCorrectionFactor'],formula:'BRW × Zeitfaktor × sachverständiger Faktor × gewichtete Fläche'},yields:[['fallback_stuttgart','Fallback Stuttgart-Zins, sachverständig anpassen',1.5,'offiziell extern','mittel']]}
];
let marketProfiles=FALLBACK_PROFILES,activeMarketProfile=null;
async function loadProfiles(){try{const r=await fetch('market-profiles.json',{cache:'no-store'});if(r.ok){const raw=await r.json();marketProfiles=raw.map(p=>({id:p.id,name:p.name||p.id,quality:p.profileQuality||p.quality||'offen',landValue:{model:p.landValue?.model,required:p.landValue?.requiredInputs||[],optional:p.landValue?.optionalInputs||[],disabled:p.landValue?.disabledInputs||[],formula:p.landValue?.formula||''},yields:(p.yields||[]).map(y=>[y.id,y.label,y.yieldPercent??null,y.sourceType||'offiziell lokal',y.confidence||'mittel',y.adjustmentRecommended])}))}}catch(e){}const id=localStorage.getItem('immowert-active-market-profile')||marketProfiles[0].id;activeMarketProfile=marketProfiles.find(p=>p.id===id)||marketProfiles[0]}
function injectMarketProfileUi(){if(document.getElementById('marketProfileBlock'))return;const body=document.getElementById('objectName')?.closest('.section-body');if(!body)return;const w=document.createElement('div');w.id='marketProfileBlock';w.className='market-profile-block full-width';w.innerHTML='<div class="section-title-inline"><strong>Marktprofil / Gutachterausschuss <span class="info-tooltip" data-tooltip="Das Marktprofil steuert lokale Bewertungslogik: Bodenwertmodell, Pflichtfelder, Zinsquelle und Datenqualität.">i</span></strong><small>datengetriebene Logik</small></div><div class="grid two compact-grid"><label>aktives Marktprofil<select id="marketProfileSelect"></select></label><label>Zinsquelle<select id="yieldSourceSelect"></select></label></div><div id="marketProfileInfo" class="market-profile-info">–</div>';body.prepend(w)}
function selectedYield(){const id=document.getElementById('yieldSourceSelect')?.value;return activeMarketProfile?.yields?.find(y=>y[0]===id)||activeMarketProfile?.yields?.[0]}
function setFieldState(id,state){const e=document.getElementById(id),l=e?.closest('label');if(!e||!l)return;l.classList.remove('profile-required','profile-disabled','profile-optional');if(state==='disabled'){e.disabled=true;l.classList.add('profile-disabled')}else{e.disabled=false;l.classList.add(state==='required'?'profile-required':'profile-optional')}}
function applyProfile(){if(!activeMarketProfile)return;const lv=activeMarketProfile.landValue||{},req=new Set(lv.required||[]),opt=new Set(lv.optional||[]),dis=new Set(lv.disabled||[]);['baseLandValuePerSqm','plotArea','buildingLandArea','gardenArea','gardenFactor','manualLocationFactor','wgfzSoll','relevantFloorArea','wgfzCorrectionFactor'].forEach(id=>setFieldState(id,dis.has(id)?'disabled':req.has(id)?'required':opt.has(id)?'optional':'optional'));const wa=document.getElementById('wgfzActive');if(wa)wa.value=lv.model==='wgfz'?'1':'0';if(typeof syncWgfzFactor==='function')syncWgfzFactor();const y=selectedYield();if(y&&Number.isFinite(y[2])&&typeof setValue==='function'){setValue('propertyYield',y[2]);setValue('propertyYieldNote',`${y[3]} · ${activeMarketProfile.name}${y[5]?' · sachverständige Anpassung empfohlen':''}`)}const info=document.getElementById('marketProfileInfo');if(info)info.innerHTML=`<strong>${esc(activeMarketProfile.name)}</strong><br>Profilqualität: ${esc(activeMarketProfile.quality)}<br>Bodenwertmodell: <code>${esc(lv.model)}</code><br>Formel: ${esc(lv.formula)}<br>Zinsquelle: ${y?esc(y[3])+' · Confidence '+esc(y[4]):'–'}${y?.[5]?' · Anpassung empfohlen':''}`}
function renderProfileUi(){const ps=document.getElementById('marketProfileSelect'),ys=document.getElementById('yieldSourceSelect');if(!ps||!ys||!activeMarketProfile)return;ps.innerHTML=marketProfiles.map(p=>`<option value="${p.id}" ${p.id===activeMarketProfile.id?'selected':''}>${esc(p.name)}</option>`).join('');ys.innerHTML=(activeMarketProfile.yields||[]).map(y=>`<option value="${y[0]}">${esc(y[1])}${Number.isFinite(y[2])?' · '+num(y[2],1)+' %':''}</option>`).join('')||'<option value="manual">manuell</option>';applyProfile()}
function installMarketProfileEvents(){document.addEventListener('change',e=>{if(e.target.id==='marketProfileSelect'){activeMarketProfile=marketProfiles.find(p=>p.id===e.target.value)||activeMarketProfile;localStorage.setItem('immowert-active-market-profile',activeMarketProfile.id);renderProfileUi();if(typeof update==='function')update()}if(e.target.id==='yieldSourceSelect'){applyProfile();if(typeof update==='function')update()}})}
async function installMarketProfiles(){await loadProfiles();injectMarketProfileUi();renderProfileUi();installMarketProfileEvents()}
function injectCss(){if(document.getElementById('ribbonOverlayCss'))return;const s=document.createElement('style');s.id='ribbonOverlayCss';s.textContent='.market-profile-block,.bog-list-block,.rnd-method-selector{margin:0 0 14px 0;padding:12px;border:1px solid #bae6fd;border-radius:14px;background:#f0f9ff}.market-profile-info{margin-top:10px;padding:10px;border-radius:10px;background:white;border:1px solid #dbeafe;font-size:13px;line-height:1.45}.profile-required{outline:2px solid rgba(14,165,233,.25);border-radius:12px}.profile-required::after{content:"Pflicht laut Marktprofil";display:block;color:#0369a1;font-size:11px;margin-top:2px}.profile-disabled{opacity:.45}.bog-items{display:grid;gap:10px}.bog-row{display:grid;grid-template-columns:150px 150px minmax(0,1fr) auto;gap:10px;align-items:end;padding:12px;border:1px solid #dbeafe;border-radius:12px;background:white}.bog-row button{height:44px}.export-memo-button{background:#0f172a;color:white;border-color:#0f172a}.result-list div span:first-child{display:inline-flex;align-items:center;gap:4px}.result-info{flex:0 0 auto;margin-left:4px}@media(max-width:900px){.bog-row{grid-template-columns:1fr}}';document.head.appendChild(s)}
function injectBogList(){if(document.getElementById('bogItemsContainer'))return;const d=document.getElementById('bogDeductions'),a=document.getElementById('bogAdditions'),body=d?.closest('.section-body');if(!body||!d||!a)return;d.closest('label').style.display='none';a.closest('label').style.display='none';const w=document.createElement('div');w.className='bog-list-block full-width';w.innerHTML='<div class="section-title-inline"><strong>boG-Einzelpositionen <span class="info-tooltip" data-tooltip="boG = besondere objektspezifische Grundstücksmerkmale. Saldo = Zuschläge − Abschläge.">i</span></strong><button type="button" id="addBogItem">+ boG hinzufügen</button></div><div id="bogItemsContainer" class="bog-items"></div><p class="hint" id="bogItemsSummary">–</p>';body.appendChild(w);renderBogItems()}
function renderBogItems(){const c=document.getElementById('bogItemsContainer');if(!c)return;c.innerHTML=bogItems.map((i,x)=>`<div class="bog-row"><label>Art<select data-bog-index="${x}" data-bog-field="type"><option value="deduct" ${i.type==='deduct'?'selected':''}>Abschlag</option><option value="add" ${i.type==='add'?'selected':''}>Zuschlag</option></select></label><label>Betrag<input type="number" min="0" step="1000" value="${i.amount||0}" data-bog-index="${x}" data-bog-field="amount"></label><label>Kommentar<input value="${esc(i.comment||'')}" data-bog-index="${x}" data-bog-field="comment"></label><button type="button" data-remove-bog="${x}">Entfernen</button></div>`).join('');updateBogSummary()}
function updateBogSummary(){syncBogTotals();const s=document.getElementById('bogItemsSummary');if(s)s.textContent=`boG saldiert: Zuschläge ${money(sumBog('add'))} − Abschläge ${money(sumBog('deduct'))} = ${money(sumBog('add')-sumBog('deduct'))}`}
function injectExport(){if(document.getElementById('exportOfferMemo'))return;const a=document.querySelector('.top-actions');if(!a)return;const b=document.createElement('button');b.type='button';b.id='exportOfferMemo';b.className='export-memo-button';b.textContent='Ankaufsmemo exportieren';a.appendChild(b)}
function exportMemo(){const cur=typeof readCase==='function'&&typeof calculate==='function'?{d:readCase(),r:calculate(readCase())}:null;if(!cur)return;const w=window.open('','_blank');if(!w)return;w.document.write(`<html><head><title>Ankaufsmemo</title><style>body{font-family:Arial;margin:32px;color:#0f172a}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid #ddd;padding:8px;text-align:left}</style></head><body><h1>LAB7784 Immowert · Ankaufsmemo</h1><p>Marktprofil: ${esc(activeMarketProfile?.name||'–')}</p><table><tr><th>Ertragswert</th><td>${money(cur.r.incomeValue)}</td></tr><tr><th>Bodenwert</th><td>${money(cur.r.landValue)}</td></tr><tr><th>Jahresrohertrag</th><td>${money(cur.r.grossIncome)}</td></tr><tr><th>Liegenschaftszins</th><td>${num(cur.d.propertyYield,2)} %</td></tr><tr><th>Zinsquelle</th><td>${esc(selectedYield()?.[3]||'–')}</td></tr></table><p>Hinweis: interne Modellrechnung, keine Verkehrswertermittlung nach §194 BauGB.</p><button onclick="window.print()">Als PDF drucken</button></body></html>`);w.document.close()}
function installUpdateHook(){if(window.__profileHook||typeof update!=='function')return;window.__profileHook=true;const old=update;update=function(...args){syncBogTotals();const r=old.apply(this,args);applyProfile();updateBogSummary();return r}}
document.addEventListener('input',e=>{const i=e.target.dataset.bogIndex,f=e.target.dataset.bogField;if(i!==undefined&&f){bogItems[i][f]=f==='amount'?parseFloat(e.target.value)||0:e.target.value;saveBogItems();updateBogSummary();if(typeof update==='function')update()}});
document.addEventListener('change',e=>{const i=e.target.dataset.bogIndex,f=e.target.dataset.bogField;if(i!==undefined&&f){bogItems[i][f]=e.target.value;saveBogItems();updateBogSummary();if(typeof update==='function')update()}});
document.addEventListener('click',e=>{if(e.target.id==='addBogItem'){bogItems.push({type:'deduct',amount:0,comment:''});saveBogItems();renderBogItems();if(typeof update==='function')update()}if(e.target.dataset.removeBog!==undefined){bogItems.splice(Number(e.target.dataset.removeBog),1);saveBogItems();renderBogItems();if(typeof update==='function')update()}if(e.target.id==='exportOfferMemo')exportMemo()});
document.addEventListener('DOMContentLoaded',async()=>{updateBrandLabel();document.querySelectorAll('[data-switch-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.switchView)));injectCss();await installMarketProfiles();injectBogList();injectExport();syncBogTotals();installUpdateHook();if(typeof update==='function')update()});
