function switchView(viewName){document.querySelectorAll('[data-view]').forEach(v=>v.classList.toggle('active',v.dataset.view===viewName));document.querySelectorAll('[data-switch-view]').forEach(b=>b.classList.toggle('active',b.dataset.switchView===viewName))}
function updateBrandLabel(){const a=document.querySelector('.ribbon-eyebrow');if(a)a.textContent='LAB7784 Immowert';const b=document.querySelector('.hero .eyebrow');if(b)b.textContent='LAB7784 Immowert · MVP';document.title='LAB7784 Immowert – Analyse & Datenerhebung'}
function money(v){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(v)||0)}
function num(v,d=2){return(Number(v)||0).toLocaleString('de-DE',{minimumFractionDigits:d,maximumFractionDigits:d})}
function val(id){const e=document.getElementById(id);return e?parseFloat(String(e.value).replace(',','.'))||0:0}
function esc(v){return String(v??'').replace(/[&<>"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[s]))}
let bogItems=JSON.parse(localStorage.getItem('immowert-bog-items')||'[]');
function saveBogItems(){localStorage.setItem('immowert-bog-items',JSON.stringify(bogItems))}
function sumBog(type){return bogItems.filter(i=>i.type===type).reduce((s,i)=>s+(Number(i.amount)||0),0)}
function syncBogTotals(){if(typeof setValue!=='function')return;setValue('bogAdditions',sumBog('add'));setValue('bogDeductions',sumBog('deduct'))}
const FALLBACK_PROFILES=[
{id:'stuttgart-2024',name:'Stuttgart 2024',quality:'hoch',landValue:{model:'wgfz',required:['baseLandValuePerSqm','plotArea','wgfzSoll','relevantFloorArea'],optional:['gardenArea','gardenFactor','manualLocationFactor'],disabled:[],formula:'BRW × Zeitfaktor × UK(WGFZ_ist) / UK(WGFZ_soll) × sonstiger Faktor'},yields:[['mfh','Reines Mehrfamilienhaus',1.5,'offiziell lokal','hoch'],['mfh20','MFH Gewerbe ≤20 %',1.4,'offiziell lokal','hoch'],['mfh50','MFH Gewerbe 21–50 %',2.1,'offiziell lokal','hoch'],['mixed','Gemischt >50 % Gewerbe',2.2,'offiziell lokal','hoch'],['office','Bürogebäude',3.6,'offiziell lokal','hoch']]},
{id:'reutlingen-2025',name:'Reutlingen 2025',quality:'mittel/hoch',landValue:{model:'no_wgfz_individual_housing',required:['baseLandValuePerSqm','plotArea','buildingLandArea'],optional:['gardenArea','gardenFactor','manualLocationFactor'],disabled:['wgfzSoll','relevantFloorArea','wgfzCorrectionFactor'],formula:'BRW × Zeitfaktor × sachverständiger Faktor; keine Regel-WGFZ-Umrechnung im individuellen Wohnungsbau'},yields:[['efh','EFH/ZFH',1.0,'offiziell lokal','hoch'],['34fh','Drei-/Vierfamilienhaus',1.2,'offiziell lokal','mittel'],['mfh','5–20-Familienhaus',1.9,'offiziell lokal','mittel'],['office','Büro/Praxis',2.9,'offiziell lokal','mittel']]},
{id:'fellbach-2022',name:'Fellbach 2022',quality:'niedrig/mittel',landValue:{model:'manual_no_local_tables',required:['baseLandValuePerSqm','plotArea','buildingLandArea'],optional:['gardenArea','gardenFactor','manualLocationFactor'],disabled:['wgfzSoll','wgfzCorrectionFactor'],formula:'BRW × Zeitfaktor × sachverständiger Faktor × gewichtete Fläche'},yields:[['fallback_stuttgart','Fallback Stuttgart-Zins, sachverständig anpassen',1.5,'offiziell extern','mittel']]}
];
let marketProfiles=FALLBACK_PROFILES,activeMarketProfile=null;
function normalizeProfile(p){return{id:p.id,name:p.name||p.id,quality:p.profileQuality||p.quality||'offen',committee:p.committee||'',source:p.source||'',landValue:{model:p.landValue?.model||'manual',required:p.landValue?.requiredInputs||p.landValue?.required||[],optional:p.landValue?.optionalInputs||p.landValue?.optional||[],disabled:p.landValue?.disabledInputs||p.landValue?.disabled||[],formula:p.landValue?.formula||''},yields:(p.yields||[]).map(y=>Array.isArray(y)?y:[y.id,y.label,y.yieldPercent??null,y.sourceType||'offiziell lokal',y.confidence||'mittel',y.adjustmentRecommended||false])}}
function denormalizeProfile(p){return{id:p.id,name:p.name,committee:p.committee||'',profileQuality:p.quality||'offen',source:p.source||'',landValue:{model:p.landValue?.model||'manual',requiredInputs:p.landValue?.required||[],optionalInputs:p.landValue?.optional||[],disabledInputs:p.landValue?.disabled||[],formula:p.landValue?.formula||''},yields:(p.yields||[]).map(y=>({id:y[0],label:y[1],yieldPercent:y[2],sourceType:y[3],confidence:y[4],adjustmentRecommended:!!y[5]}))}}
function saveProfilesLocal(){localStorage.setItem('immowert-market-profiles',JSON.stringify(marketProfiles.map(denormalizeProfile),null,2))}
async function loadProfiles(){const local=localStorage.getItem('immowert-market-profiles');if(local){try{marketProfiles=JSON.parse(local).map(normalizeProfile)}catch(e){marketProfiles=FALLBACK_PROFILES}}else{try{const r=await fetch('market-profiles.json',{cache:'no-store'});if(r.ok){const raw=await r.json();marketProfiles=raw.map(normalizeProfile)}}catch(e){marketProfiles=FALLBACK_PROFILES}}const id=localStorage.getItem('immowert-active-market-profile')||marketProfiles[0].id;activeMarketProfile=marketProfiles.find(p=>p.id===id)||marketProfiles[0]}
function profileEditorValue(){return JSON.stringify(marketProfiles.map(denormalizeProfile),null,2)}
function setProfileEditorValue(){const ta=document.getElementById('marketProfileJson');if(ta)ta.value=profileEditorValue()}
function injectMarketProfileUi(){if(document.getElementById('marketProfileBlock'))return;const body=document.getElementById('objectName')?.closest('.section-body');if(!body)return;const w=document.createElement('div');w.id='marketProfileBlock';w.className='market-profile-block full-width';w.innerHTML='<div class="section-title-inline"><strong>Marktprofil / Gutachterausschuss <span class="info-tooltip" data-tooltip="Das Marktprofil steuert lokale Bewertungslogik: Bodenwertmodell, Pflichtfelder, Zinsquelle und Datenqualität.">i</span></strong><small>datengetriebene Logik</small></div><div class="grid two compact-grid"><label>aktives Marktprofil<select id="marketProfileSelect"></select></label><label>Zinsquelle<select id="yieldSourceSelect"></select></label></div><div id="marketProfileInfo" class="market-profile-info">–</div><details class="profile-service"><summary>Service-Menü Marktdaten</summary><div class="profile-service-actions"><button type="button" id="newProfile">Neues Profil</button><button type="button" id="duplicateProfile">Profil duplizieren</button><button type="button" id="saveProfiles">JSON speichern</button><button type="button" id="exportProfiles">JSON exportieren</button><button type="button" id="importProfiles">JSON importieren</button><button type="button" id="resetProfiles">Defaults wiederherstellen</button></div><textarea id="marketProfileJson" spellcheck="false"></textarea><p class="hint" id="profileServiceStatus">Profile werden lokal im Browser gespeichert. Default-Basis bleibt market-profiles.json im Repo.</p></details>';body.prepend(w)}
function selectedYield(){const id=document.getElementById('yieldSourceSelect')?.value;return activeMarketProfile?.yields?.find(y=>y[0]===id)||activeMarketProfile?.yields?.[0]}
function setFieldState(id,state){const e=document.getElementById(id),l=e?.closest('label');if(!e||!l)return;l.classList.remove('profile-required','profile-disabled','profile-optional');if(id==='baseLandValuePerSqm')e.readOnly=true;if(state==='disabled'){e.disabled=true;l.classList.add('profile-disabled')}else{e.disabled=false;l.classList.add(state==='required'?'profile-required':'profile-optional')}}
function applyProfile(){if(!activeMarketProfile)return;const lv=activeMarketProfile.landValue||{},req=new Set(lv.required||[]),opt=new Set(lv.optional||[]),dis=new Set(lv.disabled||[]);['baseLandValuePerSqm','plotArea','buildingLandArea','gardenArea','gardenFactor','manualLocationFactor','wgfzSoll','relevantFloorArea','wgfzCorrectionFactor'].forEach(id=>setFieldState(id,dis.has(id)?'disabled':req.has(id)?'required':opt.has(id)?'optional':'optional'));const wa=document.getElementById('wgfzActive');if(wa)wa.value=lv.model==='wgfz'?'1':'0';if(typeof syncWgfzFactor==='function')syncWgfzFactor();deriveBrwFromHistory();const y=selectedYield();if(y&&Number.isFinite(y[2])&&typeof setValue==='function'){setValue('propertyYield',y[2]);setValue('propertyYieldNote',`${y[3]} · ${activeMarketProfile.name}${y[5]?' · sachverständige Anpassung empfohlen':''}`)}const info=document.getElementById('marketProfileInfo');if(info)info.innerHTML=`<strong>${esc(activeMarketProfile.name)}</strong><br>Profilqualität: ${esc(activeMarketProfile.quality)}<br>Bodenwertmodell: <code>${esc(lv.model)}</code><br>Formel: ${esc(lv.formula)}<br>Zinsquelle: ${y?esc(y[3])+' · Confidence '+esc(y[4]):'–'}${y?.[5]?' · Anpassung empfohlen':''}`}
function renderProfileUi(){const ps=document.getElementById('marketProfileSelect'),ys=document.getElementById('yieldSourceSelect');if(!ps||!ys||!activeMarketProfile)return;ps.innerHTML=marketProfiles.map(p=>`<option value="${p.id}" ${p.id===activeMarketProfile.id?'selected':''}>${esc(p.name)}</option>`).join('');ys.innerHTML=(activeMarketProfile.yields||[]).map(y=>`<option value="${y[0]}">${esc(y[1])}${Number.isFinite(y[2])?' · '+num(y[2],1)+' %':''}</option>`).join('')||'<option value="manual">manuell</option>';applyProfile();setProfileEditorValue()}
function statusMsg(t){const e=document.getElementById('profileServiceStatus');if(e)e.textContent=t}
function createEmptyProfile(){const id='custom-'+Date.now();return{id,name:'Neues Profil',quality:'manuell',committee:'',source:'',landValue:{model:'manual',required:['baseLandValuePerSqm','plotArea','buildingLandArea'],optional:['gardenArea','gardenFactor','manualLocationFactor'],disabled:['wgfzSoll','wgfzCorrectionFactor'],formula:'Bodenwert = BRW × Zeitfaktor × sachverständiger Faktor × gewichtete Fläche'},yields:[['manual_yield','Manueller Liegenschaftszins',null,'manuell','niedrig',true]]}}
function downloadProfiles(){const blob=new Blob([profileEditorValue()],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='market-profiles.local.json';a.click();URL.revokeObjectURL(a.href)}
function importProfilesPrompt(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>{const file=input.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{marketProfiles=JSON.parse(String(reader.result)).map(normalizeProfile);activeMarketProfile=marketProfiles[0];saveProfilesLocal();renderProfileUi();statusMsg('Import erfolgreich. Profile lokal gespeichert.')}catch(e){statusMsg('Import fehlgeschlagen: JSON ungültig.')}};reader.readAsText(file)};input.click()}
function installMarketProfileEvents(){document.addEventListener('change',e=>{if(e.target.id==='marketProfileSelect'){activeMarketProfile=marketProfiles.find(p=>p.id===e.target.value)||activeMarketProfile;localStorage.setItem('immowert-active-market-profile',activeMarketProfile.id);renderProfileUi();if(typeof update==='function')update()}if(e.target.id==='yieldSourceSelect'){applyProfile();if(typeof update==='function')update()}});document.addEventListener('click',e=>{if(e.target.id==='saveProfiles'){try{marketProfiles=JSON.parse(document.getElementById('marketProfileJson').value).map(normalizeProfile);activeMarketProfile=marketProfiles.find(p=>p.id===localStorage.getItem('immowert-active-market-profile'))||marketProfiles[0];saveProfilesLocal();renderProfileUi();statusMsg('Profile gespeichert.')}catch(err){statusMsg('Speichern fehlgeschlagen: JSON ungültig.')}}if(e.target.id==='newProfile'){marketProfiles.push(createEmptyProfile());activeMarketProfile=marketProfiles[marketProfiles.length-1];localStorage.setItem('immowert-active-market-profile',activeMarketProfile.id);saveProfilesLocal();renderProfileUi();statusMsg('Neues Profil angelegt.')}if(e.target.id==='duplicateProfile'){const copy=JSON.parse(JSON.stringify(activeMarketProfile));copy.id=copy.id+'-copy-'+Date.now();copy.name=copy.name+' Kopie';marketProfiles.push(copy);activeMarketProfile=copy;localStorage.setItem('immowert-active-market-profile',copy.id);saveProfilesLocal();renderProfileUi();statusMsg('Profil dupliziert.')}if(e.target.id==='exportProfiles')downloadProfiles();if(e.target.id==='importProfiles')importProfilesPrompt();if(e.target.id==='resetProfiles'){localStorage.removeItem('immowert-market-profiles');marketProfiles=FALLBACK_PROFILES;activeMarketProfile=marketProfiles[0];localStorage.setItem('immowert-active-market-profile',activeMarketProfile.id);renderProfileUi();statusMsg('Lokale Profile gelöscht. Defaults aktiv.')}})}
async function installMarketProfiles(){await loadProfiles();injectMarketProfileUi();renderProfileUi();installMarketProfileEvents()}
function brwRows(){return Array.from(document.querySelectorAll('#brwHistoryContainer .history-row')).map(row=>{const year=Number(row.querySelector('[data-history-field="year"]')?.value)||0;const value=Number(row.querySelector('[data-history-field="value"]')?.value)||0;return{year,value}}).filter(p=>p.year>0&&p.value>0).sort((a,b)=>a.year-b.year)}
function brwComputation(targetYear){const rows=brwRows();if(!rows.length)return{base:0,target:0,factor:1,info:'Keine BRW-Historie eingetragen. Bitte mindestens ein Jahr mit BRW erfassen.'};const latest=rows[rows.length-1];if(rows.length===1||targetYear===latest.year)return{base:latest.value,target:latest.value,factor:1,latest,info:`Basis-BRW aus Historie: ${latest.year} = ${money(latest.value)}/m². Bewertungsjahr ${targetYear}. Zeitfaktor = 1,000.`};const first=rows[0],span=latest.year-first.year;if(span<=0)return{base:latest.value,target:latest.value,factor:1,latest,info:`BRW-Historie nicht extrapolierbar. Basis-BRW ${latest.year} = ${money(latest.value)}/m². Zeitfaktor = 1,000.`};const gradient=(latest.value-first.value)/span,target=latest.value+gradient*(targetYear-latest.year),factor=target/latest.value;return{base:latest.value,target,factor,latest,first,gradient,info:`Basis-BRW: ${latest.year} = ${money(latest.value)}/m². Trend: (${money(latest.value)} − ${money(first.value)}) / (${latest.year} − ${first.year}) = ${money(gradient)}/m²·a. Bewertungsjahr ${targetYear}: ${money(target)}/m². Zeitfaktor = ${num(factor,3)}.`}}
function deriveBrwFromHistory(){const year=typeof getYearFromDate==='function'?getYearFromDate(document.getElementById('valuationDate')?.value):new Date().getFullYear();const c=brwComputation(year);const brw=document.getElementById('baseLandValuePerSqm');if(brw){brw.readOnly=true;brw.value=c.base?Math.round(c.base):'';const label=brw.closest('label');if(label){const firstText=label.childNodes[0];if(firstText&&firstText.nodeType===3)firstText.nodeValue='Basis-BRW aus Historie ';}}const tf=document.getElementById('timeAdjustmentFactor');if(tf)tf.value=num(c.factor,3).replace(',','.');const trend=document.getElementById('brwTrendInfo');if(trend)trend.textContent=c.info;updateLandValueChain(c)}
function injectLandValueChain(){if(document.getElementById('landValueChain'))return;const info=document.getElementById('brwTrendInfo');if(!info)return;const p=document.createElement('div');p.id='landValueChain';p.className='land-value-chain full-width';p.textContent='–';info.parentNode.insertBefore(p,info.nextSibling)}
function updateLandValueChain(c=brwComputation(new Date().getFullYear())){const el=document.getElementById('landValueChain');if(!el)return;const brwAdj=c.target||0,wgfz=val('wgfzCorrectionFactor')||1,manual=val('manualLocationFactor')||1,feature=val('landFeatureFactor')||wgfz*manual||1,building=val('buildingLandArea'),garden=val('gardenArea'),gardenFactor=val('gardenFactor'),weighted=building+garden*gardenFactor,beitragsfrei=brwAdj*feature,land=beitragsfrei*weighted;el.innerHTML=`<strong>Bodenwert transparent</strong><br>BRW Zieljahr: ${money(brwAdj)}/m² · Marktprofil-/WGFZ-/Lagefaktor: ${num(feature,3)}<br><strong>beitragsfreier Bodenwert: ${money(beitragsfrei)}/m²</strong><br>gewichtete Fläche = Bauland ${num(building,0)} m² + Garten/Nebenfläche ${num(garden,0)} m² × ${num(gardenFactor,2)} = ${num(weighted,1)} m²<br>Bodenwert = ${money(beitragsfrei)}/m² × ${num(weighted,1)} m² = <strong>${money(land)}</strong>`}
function installBrwOverride(){const brw=document.getElementById('baseLandValuePerSqm');if(brw)brw.readOnly=true;if(window.__brwOverrideInstalled||typeof calculateBrwTimeFactor!=='function')return;window.__brwOverrideInstalled=true;calculateBrwTimeFactor=function(currentBrw,valuationYear){const c=brwComputation(valuationYear);const brw=document.getElementById('baseLandValuePerSqm');if(brw&&c.base)brw.value=Math.round(c.base);setTimeout(()=>updateLandValueChain(c),0);return{factor:c.factor,info:c.info}}}
function injectCss(){if(document.getElementById('ribbonOverlayCss'))return;const s=document.createElement('style');s.id='ribbonOverlayCss';s.textContent='.market-profile-block,.bog-list-block,.rnd-method-selector{margin:0 0 14px 0;padding:12px;border:1px solid #bae6fd;border-radius:14px;background:#f0f9ff}.market-profile-info{margin-top:10px;padding:10px;border-radius:10px;background:white;border:1px solid #dbeafe;font-size:13px;line-height:1.45}.profile-service{margin-top:10px}.profile-service summary{cursor:pointer;font-weight:800}.profile-service-actions{display:flex;flex-wrap:wrap;gap:8px;margin:10px 0}.profile-service textarea{width:100%;min-height:300px;font-family:ui-monospace,Consolas,monospace;font-size:12px;border:1px solid #bae6fd;border-radius:12px;padding:10px;background:#fff}.profile-required{outline:2px solid rgba(14,165,233,.25);border-radius:12px}.profile-required::after{content:"Pflicht laut Marktprofil";display:block;color:#0369a1;font-size:11px;margin-top:2px}.profile-disabled{opacity:.45}.land-value-chain{margin-top:10px;padding:12px;border-radius:12px;background:white;border:1px solid #bae6fd;font-size:13px;line-height:1.45}.bog-items{display:grid;gap:10px}.bog-row{display:grid;grid-template-columns:150px 150px minmax(0,1fr) auto;gap:10px;align-items:end;padding:12px;border:1px solid #dbeafe;border-radius:12px;background:white}.bog-row button{height:44px}.export-memo-button{background:#0f172a;color:white;border-color:#0f172a}.result-list div span:first-child{display:inline-flex;align-items:center;gap:4px}.result-info{flex:0 0 auto;margin-left:4px}@media(max-width:900px){.bog-row{grid-template-columns:1fr}}';document.head.appendChild(s)}
function injectBogList(){if(document.getElementById('bogItemsContainer'))return;const d=document.getElementById('bogDeductions'),a=document.getElementById('bogAdditions'),body=d?.closest('.section-body');if(!body||!d||!a)return;d.closest('label').style.display='none';a.closest('label').style.display='none';const w=document.createElement('div');w.className='bog-list-block full-width';w.innerHTML='<div class="section-title-inline"><strong>boG-Einzelpositionen <span class="info-tooltip" data-tooltip="boG = besondere objektspezifische Grundstücksmerkmale. Saldo = Zuschläge − Abschläge.">i</span></strong><button type="button" id="addBogItem">+ boG hinzufügen</button></div><div id="bogItemsContainer" class="bog-items"></div><p class="hint" id="bogItemsSummary">–</p>';body.appendChild(w);renderBogItems()}
function renderBogItems(){const c=document.getElementById('bogItemsContainer');if(!c)return;c.innerHTML=bogItems.map((i,x)=>`<div class="bog-row"><label>Art<select data-bog-index="${x}" data-bog-field="type"><option value="deduct" ${i.type==='deduct'?'selected':''}>Abschlag</option><option value="add" ${i.type==='add'?'selected':''}>Zuschlag</option></select></label><label>Betrag<input type="number" min="0" step="1000" value="${i.amount||0}" data-bog-index="${x}" data-bog-field="amount"></label><label>Kommentar<input value="${esc(i.comment||'')}" data-bog-index="${x}" data-bog-field="comment"></label><button type="button" data-remove-bog="${x}">Entfernen</button></div>`).join('');updateBogSummary()}
function updateBogSummary(){syncBogTotals();const s=document.getElementById('bogItemsSummary');if(s)s.textContent=`boG saldiert: Zuschläge ${money(sumBog('add'))} − Abschläge ${money(sumBog('deduct'))} = ${money(sumBog('add')-sumBog('deduct'))}`}
function injectExport(){if(document.getElementById('exportOfferMemo'))return;const a=document.querySelector('.top-actions');if(!a)return;const b=document.createElement('button');b.type='button';b.id='exportOfferMemo';b.className='export-memo-button';b.textContent='Ankaufsmemo exportieren';a.appendChild(b)}
function exportMemo(){const cur=typeof readCase==='function'&&typeof calculate==='function'?{d:readCase(),r:calculate(readCase())}:null;if(!cur)return;const w=window.open('','_blank');if(!w)return;w.document.write(`<html><head><title>Ankaufsmemo</title><style>body{font-family:Arial;margin:32px;color:#0f172a}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid #ddd;padding:8px;text-align:left}</style></head><body><h1>LAB7784 Immowert · Ankaufsmemo</h1><p>Marktprofil: ${esc(activeMarketProfile?.name||'–')}</p><table><tr><th>Ertragswert</th><td>${money(cur.r.incomeValue)}</td></tr><tr><th>Bodenwert</th><td>${money(cur.r.landValue)}</td></tr><tr><th>Jahresrohertrag</th><td>${money(cur.r.grossIncome)}</td></tr><tr><th>Liegenschaftszins</th><td>${num(cur.d.propertyYield,2)} %</td></tr><tr><th>Zinsquelle</th><td>${esc(selectedYield()?.[3]||'–')}</td></tr></table><p>Hinweis: interne Modellrechnung, keine Verkehrswertermittlung nach §194 BauGB.</p><button onclick="window.print()">Als PDF drucken</button></body></html>`);w.document.close()}
function installUpdateHook(){if(window.__profileHook||typeof update!=='function')return;window.__profileHook=true;const old=update;update=function(...args){syncBogTotals();deriveBrwFromHistory();const r=old.apply(this,args);applyProfile();updateBogSummary();deriveBrwFromHistory();return r}}
document.addEventListener('input',e=>{const i=e.target.dataset.bogIndex,f=e.target.dataset.bogField;if(i!==undefined&&f){bogItems[i][f]=f==='amount'?parseFloat(e.target.value)||0:e.target.value;saveBogItems();updateBogSummary();if(typeof update==='function')update()}if(e.target.dataset.historyField!==undefined)setTimeout(deriveBrwFromHistory,0)});
document.addEventListener('change',e=>{const i=e.target.dataset.bogIndex,f=e.target.dataset.bogField;if(i!==undefined&&f){bogItems[i][f]=e.target.value;saveBogItems();updateBogSummary();if(typeof update==='function')update()}if(e.target.dataset.historyField!==undefined)setTimeout(deriveBrwFromHistory,0)});
document.addEventListener('click',e=>{if(e.target.id==='addBogItem'){bogItems.push({type:'deduct',amount:0,comment:''});saveBogItems();renderBogItems();if(typeof update==='function')update()}if(e.target.dataset.removeBog!==undefined){bogItems.splice(Number(e.target.dataset.removeBog),1);saveBogItems();renderBogItems();if(typeof update==='function')update()}if(e.target.id==='exportOfferMemo')exportMemo();if(e.target.id==='addBrwHistory')setTimeout(deriveBrwFromHistory,0)});
document.addEventListener('DOMContentLoaded',async()=>{updateBrandLabel();document.querySelectorAll('[data-switch-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.switchView)));injectCss();await installMarketProfiles();injectBrwHint();injectLandValueChain();installBrwOverride();deriveBrwFromHistory();injectBogList();injectExport();syncBogTotals();installUpdateHook();if(typeof update==='function')update()});
function injectBrwHint(){const brw=document.getElementById('baseLandValuePerSqm');const label=brw?.closest('label');if(!brw||!label||document.getElementById('brwDerivedHint'))return;brw.readOnly=true;const s=document.createElement('small');s.id='brwDerivedHint';s.textContent='readonly: wird aus dem jüngsten Eintrag der BRW-Historie abgeleitet';label.appendChild(s)}
